const config = {
    simNet: {
        apiKey: 'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTAyMjQyNzgsImlhdCI6MTY1ODY4ODI3OCwicmF5IjoiNzAxM2E0MTczMGE4ZTI4NWVlZWMxOWE0MDQwMzIyOGYiLCJzdWIiOjExMjY0ODB9.vhj8Ig68dbao4hTV-XQAyh84Ulx10SgKsC-w1F7qbswwbzBiKaKRf6dHfo36XOSAFuwFYyCSt4SN1v6FN5OhaJlOHXPgdZ5xVqrAPG51XoScgMr8rs8AX4wuQnCXKq-OSkVMeOyggZGCydrKTV9d64ku9E9iYm-KB8knK1uKIie8ub6Ydn2WD14b-V3HOSUSu209F5uayDk_Z18VYAnLfRvY_L0v_1n0k97pqO8enFMVTabomOuBlSX-KA4qlVWZXF2N9vVmi50k16l0LLBNBEfDxyi8wICKO8ETv1GuwLv2EMHBnLrhB3ylegPjC9-NGDgASzpFNJfjjetG5aqISw',
        delay: 180,
        rubLimit: 28,
        country: ["turkey", "mongolia", "vietnam"],
        url: 'https://5sim.net'
    },
    smsAct: {
        apiKey: 'efA126ffd10bb1b2723b318d36dd471f',
        delay: 120,
        rubLimit: 28,
        country: ["russia", "ukraine", "kazakhstan", "china", "philippines", "myanmar", "indonesia", "malaysia", "kenya", "tanzania", "vietnam", "kyrgyzstan", "usa (virtual)", "israel", "hongkong", "poland", "england", "dcongo", "nigeria", "macao", "egypt", "india", "ireland", "cambodia", "laos", "haiti", "ivory", "gambia", "serbia", "yemen", "southafrica", "romania", "colombia", "estonia", "canada", "morocco", "ghana", "argentina", "uzbekistan", "cameroon", "chad", "germany", "lithuania", "croatia", "sweden", "iraq", "netherlands", "latvia", "austria", "belarus", "thailand", "saudiarabia", "mexico", "taiwan", "spain", "algeria", "slovenia", "bangladesh", "senegal", "turkey", "czech", "srilanka", "peru", "pakistan", "newzealand", "guinea", "mali", "venezuela", "ethiopia", "mongolia", "brazil", "afghanistan", "uganda", "angola", "cyprus", "france", "papua", "mozambique", "nepal", "belgium", "bulgaria", "hungary", "moldova", "italy", "paraguay", "honduras", "tunisia", "nicaragua", "timorleste", "bolivia", "costarica", "guatemala", "uae", "zimbabwe", "puertorico", "togo", "kuwait", "salvador", "libyan", "jamaica", "trinidad", "ecuador", "swaziland", "oman", "bosnia", "dominican", "qatar", "panama", "mauritania", "sierraleone", "jordan", "portugal", "barbados", "burundi", "benin", "brunei", "bahamas", "botswana", "belize", "caf", "dominica", "grenada", "georgia", "greece", "guineabissau", "guyana", "iceland", "comoros", "saintkitts", "liberia", "lesotho", "malawi", "namibia", "niger", "rwanda", "slovakia", "suriname", "tajikistan", "monaco", "bahrain", "reunion", "zambia", "armenia", "somalia", "congo", "chile", "furkinafaso", "lebanon", "gabon", "albania", "uruguay", "mauritius", "bhutan", "maldives", "guadeloupe", "turkmenistan", "frenchguiana", "finland", "saintlucia", "luxembourg", "saintvincentgrenadines", "equatorialguinea", "djibouti", "antiguabarbuda", "caymanislands", "montenegro", "denmark", "switzerland", "norway", "australia", "eritrea", "southsudan", "saotomeandprincipe", "aruba", "montserrat", "anguilla", "northmacedonia", "seychelles", "newcaledonia", "capeverde", "usa"],
        url: 'https://sms-activate.org/'
    },
    smsMan:{
        apiKey: 'XL-FsyeHnOMgXuvInZOYd0hPyN51eXGh',
        delay: 55,
        rubLimit: 28,
        country: ["russia", "ukraine", "kazakhstan", "china", "philippines", "myanmar", "indonesia", "malaysia", "kenya", "tanzania", "vietnam", "kyrgyzstan", "usa (virtual)", "israel", "hongkong", "poland", "england", "dcongo", "nigeria", "macao", "egypt", "india", "ireland", "cambodia", "laos", "haiti", "ivory", "gambia", "serbia", "yemen", "southafrica", "romania", "colombia", "estonia", "canada", "morocco", "ghana", "argentina", "uzbekistan", "cameroon", "chad", "germany", "lithuania", "croatia", "sweden", "iraq", "netherlands", "latvia", "austria", "belarus", "thailand", "saudiarabia", "mexico", "taiwan", "spain", "algeria", "slovenia", "bangladesh", "senegal", "turkey", "czech", "srilanka", "peru", "pakistan", "newzealand", "guinea", "mali", "venezuela", "ethiopia", "mongolia", "brazil", "afghanistan", "uganda", "angola", "cyprus", "france", "papua", "mozambique", "nepal", "belgium", "bulgaria", "hungary", "moldova", "italy", "paraguay", "honduras", "tunisia", "nicaragua", "timorleste", "bolivia", "costarica", "guatemala", "uae", "zimbabwe", "puertorico", "togo", "kuwait", "salvador", "libyan", "jamaica", "trinidad", "ecuador", "swaziland", "oman", "bosnia", "dominican", "qatar", "panama", "mauritania", "sierraleone", "jordan", "portugal", "barbados", "burundi", "benin", "brunei", "bahamas", "botswana", "belize", "caf", "dominica", "grenada", "georgia", "greece", "guineabissau", "guyana", "iceland", "comoros", "saintkitts", "liberia", "lesotho", "malawi", "namibia", "niger", "rwanda", "slovakia", "suriname", "tajikistan", "monaco", "bahrain", "reunion", "zambia", "armenia", "somalia", "congo", "chile", "furkinafaso", "lebanon", "gabon", "albania", "uruguay", "mauritius", "bhutan", "maldives", "guadeloupe", "turkmenistan", "frenchguiana", "finland", "saintlucia", "luxembourg", "saintvincentgrenadines", "equatorialguinea", "djibouti", "antiguabarbuda", "caymanislands", "montenegro", "denmark", "switzerland", "norway", "australia", "eritrea", "southsudan", "saotomeandprincipe", "aruba", "montserrat", "anguilla", "northmacedonia", "seychelles", "newcaledonia", "capeverde", "usa"],
        url: 'https://sms-man.com/'
    }
}
module.exports = config
